# Generated by Django 5.1.6 on 2025-03-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['theme'], 'permissions': [('can_manage_messages', 'Может управлять сообщениями')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
