# Generated by Django 5.1.6 on 2025-03-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('faile', 'Не успешно')], max_length=10, verbose_name='Статус'),
        ),
    ]
