# Generated by Django 5.1.6 on 2025-03-04 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('newsletter_recipient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Вреимя окончания')),
                ('state', models.CharField(choices=[('compl', 'Завепшена'), ('create', 'Создана'), ('start', 'Запущена')], max_length=6, verbose_name='статус')),
                ('message_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Сообщение', to='message.message')),
                ('recipients', models.ManyToManyField(to='newsletter_recipient.newsletter')),
            ],
        ),
    ]
