# Generated by Django 5.1.6 on 2025-03-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_distribution_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='state',
            field=models.CharField(choices=[('compl', 'Завепшена'), ('create', 'Создана'), ('start', 'Запущена')], max_length=20, verbose_name='статус'),
        ),
    ]
