# Generated by Django 5.1.6 on 2025-03-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=40, unique=True, verbose_name='Введите почту')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('comment', models.TextField(verbose_name='коментарийучше')),
            ],
            options={
                'verbose_name': 'получатель рассылки',
                'verbose_name_plural': 'получатели рассылки',
                'ordering': ['name'],
            },
        ),
    ]
