# Generated by Django 5.1.6 on 2025-03-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_recipient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['name'], 'permissions': [('can_manage_newsletters', 'Может управлять получателями рассылки')], 'verbose_name': 'получатель рассылки', 'verbose_name_plural': 'получатели рассылки'},
        ),
    ]
